[2024-05-26T20:50:25.016+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T20:50:25.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_bbc_website_dag.scrape_bbc_website_task manual__2024-05-26T20:50:15.020350+00:00 [queued]>
[2024-05-26T20:50:25.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_bbc_website_dag.scrape_bbc_website_task manual__2024-05-26T20:50:15.020350+00:00 [queued]>
[2024-05-26T20:50:25.269+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T20:50:25.333+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_bbc_website_task> on 2024-05-26 20:50:15.020350+00:00
[2024-05-26T20:50:25.345+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_bbc_website_dag', 'scrape_bbc_website_task', 'manual__2024-05-26T20:50:15.020350+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmpp_lbx3mx']
[2024-05-26T20:50:25.349+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask scrape_bbc_website_task
[2024-05-26T20:50:25.340+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2024-05-26T20:50:25.544+0000] {task_command.py:426} INFO - Running <TaskInstance: scrape_bbc_website_dag.scrape_bbc_website_task manual__2024-05-26T20:50:15.020350+00:00 [running]> on host 701b5a94ba50
[2024-05-26T20:50:25.843+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrape_bbc_website_dag' AIRFLOW_CTX_TASK_ID='scrape_bbc_website_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-26T20:50:15.020350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-26T20:50:15.020350+00:00'
[2024-05-26T20:50:25.845+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T20:50:26.496+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T20:50:26.497+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/welcome_dag.py", line 21, in scrape_bbc_website
    driver = webdriver.Firefox(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

[2024-05-26T20:50:26.524+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=scrape_bbc_website_dag, task_id=scrape_bbc_website_task, run_id=manual__2024-05-26T20:50:15.020350+00:00, execution_date=20240526T205015, start_date=20240526T205025, end_date=20240526T205026
[2024-05-26T20:50:26.573+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task scrape_bbc_website_task (Message: Process unexpectedly closed with status 1
; 170)
[2024-05-26T20:50:26.613+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-26T20:50:26.643+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T20:50:26.645+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
